### ISSUE TITLE
Step 5 in "Preparation" fails

### ISSUE THREAD

**Issue by WJLiddy** [nanflasted/TekinBot#1]
I followed steps 1-4 without issue. However, step 5 in "preparation" says:

Run `make dev` to make a local server instance so you could curl and test your changes

When I do this, this is the output I get

![image](https://user-images.githubusercontent.com/8826899/38653454-d90cea70-3dd8-11e8-8bf6-58b577d4bf06.png)

Do I need to have the database prepared in order to test my module (even if my module doesn't use the database?). If so, that should be added to the readme as a preparation step.

**Comment by nanflasted** [comment]
The lack of separation between dev environment and actual build is a serious issue with TekinBot, due to its history; will try to fix this issue along with other dev environment problems. 

Documentation can be a bit clearer too.

**Comment by nanflasted** [comment]
There's a bug introduced by #2 related to this issue; pushing a branch to fix.

**Comment by nanflasted** [comment]
Fixed in #2 and #4, closed.
